using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using Pickle.Abstractions;

namespace Pickle.Tui.Panels.Settings;

public enum SettingKind
{
    Bool,
    Integer,
    Number,
    Text,
    Choice,
    List,
}

/// <summary>One editable config value, addressed by its dotted camelCase path (e.g. <c>editor.autosuggestions</c>).</summary>
public sealed record SettingField(string Category, string Path, string Label, SettingKind Kind, bool Nullable, IReadOnlyList<string> Choices);

/// <summary>
/// Settings fields generated by reflection over the <see cref="PickleConfig"/> section classes, plus reading,
/// validating and writing their values through <see cref="IConfigStore"/>.
/// </summary>
public static class SettingsModel
{
    public const string ThemeCategory = "Theme";
    public const string KeyBindingsCategory = "Key bindings";

    private static readonly Dictionary<string, string[]> KnownChoices = new(StringComparer.OrdinalIgnoreCase)
    {
        ["editor.bellStyle"] = ["none", "audible", "visual"],
        ["terminal.cursorShape"] = ["bar", "vintage", "underscore", "filledBox", "emptyBox", "doubleUnderscore"],
        ["sync.backend"] = ["none", "folder", "git"],
    };

    /// <summary>Theme, the config sections in declaration order, then key bindings.</summary>
    public static IReadOnlyList<string> Categories { get; } =
    [
        ThemeCategory,
        .. SectionProperties().Select(p => Humanize(p.Name)),
        KeyBindingsCategory,
    ];

    public static IReadOnlyList<SettingField> Fields(IPickleContext pickle)
    {
        var fields = new List<SettingField>
        {
            new(ThemeCategory, "theme", "Theme", SettingKind.Choice, false, pickle.Themes.Available),
        };

        foreach (var section in SectionProperties())
        {
            var category = Humanize(section.Name);
            foreach (var property in section.PropertyType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                if (!property.CanRead || !property.CanWrite)
                {
                    continue;
                }

                var path = CamelCase(section.Name) + "." + CamelCase(property.Name);
                var type = property.PropertyType;
                var underlying = System.Nullable.GetUnderlyingType(type);
                var nullable = underlying is not null || (!type.IsValueType && new NullabilityInfoContext().Create(property).WriteState == NullabilityState.Nullable);
                type = underlying ?? type;
                var kind = type switch
                {
                    _ when KnownChoices.ContainsKey(path) => SettingKind.Choice,
                    _ when type == typeof(bool) => SettingKind.Bool,
                    _ when type == typeof(int) || type == typeof(long) => SettingKind.Integer,
                    _ when type == typeof(double) || type == typeof(float) || type == typeof(decimal) => SettingKind.Number,
                    _ when type == typeof(string) => SettingKind.Text,
                    _ when typeof(IEnumerable<string>).IsAssignableFrom(type) => SettingKind.List,
                    _ => (SettingKind?)null,
                };
                if (kind is { } k)
                {
                    fields.Add(new SettingField(category, path, Humanize(property.Name), k, nullable, KnownChoices.TryGetValue(path, out var choices) ? choices : []));
                }
            }
        }

        return fields;
    }

    /// <summary>Current value as display text ("true", "4000", "a, b").</summary>
    public static string Read(IPickleContext pickle, SettingField field)
    {
        if (field.Path == "theme")
        {
            return pickle.Themes.Current.Name;
        }

        if (pickle.Config.GetValue(field.Path) is not { } element)
        {
            return string.Empty;
        }

        return element.ValueKind switch
        {
            JsonValueKind.String => element.GetString() ?? string.Empty,
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            JsonValueKind.Null or JsonValueKind.Undefined => string.Empty,
            JsonValueKind.Array => string.Join(", ", element.EnumerateArray().Select(e => e.ValueKind == JsonValueKind.String ? e.GetString() : e.GetRawText())),
            _ => element.GetRawText(),
        };
    }

    /// <summary>Validates user input and produces the JSON for <see cref="IConfigStore.SetValue"/>; returns an error or null.</summary>
    public static string? TryConvert(SettingField field, string input, out string json)
    {
        json = string.Empty;
        var text = input.Trim();
        if (text.Length == 0 && field.Nullable && field.Kind is not SettingKind.List)
        {
            json = "null";
            return null;
        }

        switch (field.Kind)
        {
            case SettingKind.Bool:
                if (!bool.TryParse(text, out var b))
                {
                    return $"{field.Label} must be true or false.";
                }

                json = b ? "true" : "false";
                return null;
            case SettingKind.Integer:
                if (!long.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var l) || l < 0 || l > int.MaxValue)
                {
                    return $"{field.Label} must be a whole number ≥ 0.";
                }

                json = l.ToString(CultureInfo.InvariantCulture);
                return null;
            case SettingKind.Number:
                if (!double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var d) || double.IsNaN(d) || double.IsInfinity(d))
                {
                    return $"{field.Label} must be a number.";
                }

                json = d.ToString("R", CultureInfo.InvariantCulture);
                return null;
            case SettingKind.Choice:
                var choice = field.Choices.FirstOrDefault(c => string.Equals(c, text, StringComparison.OrdinalIgnoreCase));
                if (choice is null)
                {
                    return $"{field.Label} must be one of: {string.Join(", ", field.Choices)}.";
                }

                json = JsonSerializer.Serialize(choice);
                return null;
            case SettingKind.List:
                json = JsonSerializer.Serialize(text.Split([',', ';'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries));
                return null;
            default:
                json = JsonSerializer.Serialize(text);
                return null;
        }
    }

    /// <summary>Validates and saves; returns an error message or null. Theme changes apply live.</summary>
    public static string? Write(IPickleContext pickle, SettingField field, string input)
    {
        if (TryConvert(field, input, out var json) is { } error)
        {
            return error;
        }

        try
        {
            if (field.Path == "theme")
            {
                pickle.Themes.Apply(JsonSerializer.Deserialize<string>(json)!);
            }
            else
            {
                pickle.Config.SetValue(field.Path, json);
            }
        }
        catch (Exception ex) when (ex is JsonException or ArgumentException or InvalidOperationException or IOException)
        {
            return ex.Message;
        }

        return null;
    }

    public static string Humanize(string name)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (i > 0 && char.IsUpper(c) && !char.IsUpper(name[i - 1]))
            {
                sb.Append(' ').Append(char.ToLowerInvariant(c));
            }
            else
            {
                sb.Append(i == 0 ? char.ToUpperInvariant(c) : c);
            }
        }

        return sb.ToString();
    }

    private static string CamelCase(string name) => char.ToLowerInvariant(name[0]) + name[1..];

    private static IEnumerable<PropertyInfo> SectionProperties() =>
        typeof(PickleConfig).GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.PropertyType.IsClass && p.PropertyType.Name.EndsWith("Settings", StringComparison.Ordinal))
            .OrderBy(p => p.MetadataToken);
}
