using System.Reflection;
using Pickle.Abstractions;
using Pickle.Abstractions.Services;
using Pickle.Tui;

namespace Pickle.Modules.Themes;

/// <summary>
/// Twelve extra themes (Monokai, One Dark/Light, Ayu Mirage, Everforest, Kanagawa, GitHub Dark/Light, Oxocarbon, Zenburn,
/// Material Ocean, Night Owl). They are copied into the themes folder when the module loads (never over a file you
/// edited), so they behave like your own themes: <c>pk theme list</c>, the gallery and <c>theme auto</c> all see them.
/// The JSON is generated by <c>scripts/gen-theme-packs.py</c>.
/// </summary>
public sealed class ThemePacksModule : IPicklePlugin
{
    public const string ModuleId = "themes";
    private const string ResourcePrefix = "Pickle.Modules.Themes.";

    public static ModuleDescriptor Descriptor { get; } = new()
    {
        Id = ModuleId,
        Name = "Theme packs",
        Description = "Twelve extra themes: Monokai, One Dark, Kanagawa, GitHub, Oxocarbon, Night Owl, …",
        Create = () => new ThemePacksModule(),
        Provides = ["pk themepack", "12 themes (pk theme list)"],
    };

    string IPicklePlugin.Id => "pickle." + ModuleId;

    public string DisplayName => Descriptor.Name;

    public string Description => Descriptor.Description;

    public static IReadOnlyList<string> ThemeNames { get; } =
    [
        .. typeof(ThemePacksModule).Assembly.GetManifestResourceNames()
            .Where(n => n.StartsWith(ResourcePrefix, StringComparison.Ordinal) && n.EndsWith(".json", StringComparison.Ordinal))
            .Select(n => n[ResourcePrefix.Length..^5])
            .Order(StringComparer.Ordinal),
    ];

    public void Initialize(IPickleContext context)
    {
        Install(context.Paths.ThemesDir, overwrite: false, context.Log);
        context.Commands.Register(new ThemePackCommand());
    }

    /// <summary>Copies the pack's themes into <paramref name="directory"/>; existing files are kept unless <paramref name="overwrite"/>. Returns the names written.</summary>
    public static IReadOnlyList<string> Install(string directory, bool overwrite, IPickleLogger? log = null)
    {
        var written = new List<string>();
        Directory.CreateDirectory(directory);
        foreach (var name in ThemeNames)
        {
            var path = Path.Combine(directory, name + ".json");
            if (File.Exists(path) && !overwrite)
            {
                continue;
            }

            using var stream = typeof(ThemePacksModule).Assembly.GetManifestResourceStream(ResourcePrefix + name + ".json");
            if (stream is null)
            {
                continue;
            }

            try
            {
                using var file = File.Create(path);
                stream.CopyTo(file);
                written.Add(name);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                log?.Warn("themes", $"Could not write {path}", ex);
            }
        }

        return written;
    }

    /// <summary>Removes the pack's theme files that still match the original (a file you edited is left alone). Returns the names removed.</summary>
    public static IReadOnlyList<string> Remove(string directory)
    {
        var removed = new List<string>();
        foreach (var name in ThemeNames)
        {
            var path = Path.Combine(directory, name + ".json");
            if (!File.Exists(path))
            {
                continue;
            }

            using var stream = typeof(ThemePacksModule).Assembly.GetManifestResourceStream(ResourcePrefix + name + ".json")!;
            using var reader = new StreamReader(stream);
            if (File.ReadAllText(path) == reader.ReadToEnd())
            {
                File.Delete(path);
                removed.Add(name);
            }
        }

        return removed;
    }
}

/// <summary><c>pk themepack list|install|remove</c>.</summary>
internal sealed class ThemePackCommand : PickleCommandBase
{
    public override string Name => "themepack";

    public override string Description => "The theme pack's themes: list, restore the originals, or remove them";

    public override string Usage => "pk themepack [list | install [--force] | remove]";

    protected override Task<int> RunAsync(CommandOutput output, IReadOnlyList<string> raw, CancellationToken cancellationToken)
    {
        var args = CommandArgs.Parse(raw);
        var directory = output.Pickle.Paths.ThemesDir;
        switch (args.Arg(0)?.ToLowerInvariant() ?? "list")
        {
            case "list":
                foreach (var name in ThemePacksModule.ThemeNames)
                {
                    output.Object(new { Theme = name, Installed = File.Exists(Path.Combine(directory, name + ".json")) });
                }

                return Task.FromResult(0);
            case "install":
                var written = ThemePacksModule.Install(directory, args.Has("force"), output.Pickle.Log);
                output.Success(written.Count == 0 ? "Nothing to do (every theme is already there; --force restores the originals)." : $"Wrote {written.Count} theme(s): {string.Join(", ", written)}.");
                return Task.FromResult(0);
            case "remove":
                var removed = ThemePacksModule.Remove(directory);
                output.Success($"Removed {removed.Count} unchanged theme(s); edited ones were kept. 'pk module disable themes' stops them coming back.");
                return Task.FromResult(0);
            default:
                return Task.FromResult(UsageError(output));
        }
    }
}
