#!/usr/bin/env python3
"""Turns packaging/modules.json (the optional modules) into installer pieces.

  modules.py wix                    the WiX fragment: one feature per module (off by default), each writing
                                    HKLM\\Software\\Pickle\\Modules\\<id> = 1, which Pickle reads at start
  modules.py rpm-spec <pickle.spec> the spec with its @@MODULE_*@@ marker lines replaced by one pickle-module-<id>
                                    sub-package per module (a marker file in /etc/pickle/modules.d) and pickle-modules-all
  modules.py check                  validates the JSON

Standard library only; run by packaging/wix/build-msi.ps1 and packaging/rpm/build-rpm.sh.
"""
import json
import pathlib
import re
import sys
from xml.sax.saxutils import quoteattr

ROOT = pathlib.Path(__file__).resolve().parent
PLATFORMS = {"windows", "linux", "macos"}
ID = re.compile(r"^[A-Za-z][A-Za-z0-9-]{0,39}$")
PACKAGE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._+-]*$")


def load(path=None):
    data = json.loads(pathlib.Path(path or ROOT / "modules.json").read_text(encoding="utf-8"))
    modules = data["modules"]
    seen = set()
    for m in modules:
        if not ID.match(m["id"]):
            raise SystemExit(f"modules.json: '{m['id']}' is not a module id")
        if m["id"] in seen:
            raise SystemExit(f"modules.json: '{m['id']}' is listed twice")
        seen.add(m["id"])
        for key in ("name", "description"):
            if not m.get(key, "").strip() or "\n" in m[key]:
                raise SystemExit(f"modules.json: '{m['id']}' needs a one-line {key}")
        if not m.get("platforms") or not set(m["platforms"]) <= PLATFORMS:
            raise SystemExit(f"modules.json: '{m['id']}' platforms must be some of {sorted(PLATFORMS)}")
        for package in m.get("rpmRecommends", []):
            if not PACKAGE.match(package):
                raise SystemExit(f"modules.json: '{package}' is not an RPM package name")
    return modules


def wix_id(module_id):
    return module_id.replace("-", "_")


def wix_property(module_id):
    # A property set by a search must be public, so its name is all upper case.
    return "PREVMODULE_" + wix_id(module_id).upper()


def wix(modules):
    windows = [m for m in modules if "windows" in m["platforms"]]
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by packaging/modules.py from packaging/modules.json. Do not edit. -->",
        '<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">',
        "  <Fragment>",
    ]
    for m in windows:
        i = wix_id(m["id"])
        lines += [
            # A major upgrade installs the new product with default selections: the value an earlier version wrote tells
            # which modules were chosen, so they stay chosen.
            f'    <Property Id="{wix_property(m["id"])}">',
            f'      <RegistrySearch Id="PrevModuleSearch_{i}" Root="HKLM" Key="Software\\Pickle\\Modules" Name={quoteattr(m["id"])} Type="raw" Bitness="always64" />',
            "    </Property>",
        ]
    lines.append('    <DirectoryRef Id="INSTALLFOLDER">')
    for m in windows:
        i = wix_id(m["id"])
        lines += [
            f'      <Component Id="ModuleRegistry_{i}">',
            f'        <RegistryValue Root="HKLM" Key="Software\\Pickle\\Modules" Name={quoteattr(m["id"])} Type="integer" Value="1" KeyPath="yes" />',
            "      </Component>",
        ]
    lines.append("    </DirectoryRef>")
    lines += [
        '    <Feature Id="ModulesFeature" Level="1" Display="expand" Title="Optional modules"',
        '             Description="Extra panels and commands that install with Pickle but stay off until you select them: nmap, Docker, Kubernetes, GitHub, a secrets vault and more. pk module setup changes the choice later.">',
    ]
    for m in windows:
        i = wix_id(m["id"])
        lines += [
            f'      <Feature Id="Module_{i}" Level="2" Title={quoteattr(m["name"])} Description={quoteattr(m["description"])}>',
            f'        <Level Value="1" Condition="{wix_property(m["id"])}" />',
            f'        <ComponentRef Id="ModuleRegistry_{i}" />',
            "      </Feature>",
        ]
    lines += ["    </Feature>", "  </Fragment>", "</Wix>", ""]
    return "\n".join(lines)


def rpm_text(text):
    return text.replace("%", "%%")


def rpm_sections(modules):
    linux = [m for m in modules if "linux" in m["platforms"]]
    packages, install, files = [], [], []
    for m in linux:
        name = f"pickle-module-{m['id']}"
        packages += [
            f"%package -n {name}",
            f"Summary:        Pickle module: {rpm_text(m['name'])}",
            "BuildArch:      noarch",
            "Requires:       pickle = %{version}-%{release}",
        ]
        packages += [f"Recommends:     {package}" for package in m.get("rpmRecommends", [])]
        description = rpm_text(m["description"] if m["description"][-1] in ".…" else m["description"] + ".")
        packages += ["", f"%description -n {name}", description, "Installing this package turns the module on for every user; 'pk module disable' turns it off for one.", ""]
        install.append(f"install -Dm0644 /dev/null %{{buildroot}}/etc/pickle/modules.d/{m['id']}")
        files += [f"%files -n {name}", f"/etc/pickle/modules.d/{m['id']}", ""]
    packages += [
        "%package -n pickle-modules-all",
        "Summary:        Pickle: every optional module",
        "BuildArch:      noarch",
        "Requires:       pickle = %{version}-%{release}",
    ]
    packages += [f"Requires:       pickle-module-{m['id']} = %{{version}}-%{{release}}" for m in linux]
    packages += ["", "%description -n pickle-modules-all", "Installs every optional Pickle module (nmap, Docker, Kubernetes, GitHub, vault, WSL and containers, …).", ""]
    # A package whose %files is empty is not built at all, so the meta package carries one small file.
    install.append("install -d %{buildroot}%{_docdir}/pickle-modules-all")
    install.append("echo 'This meta package only depends on every optional Pickle module (pickle-module-*).' > %{buildroot}%{_docdir}/pickle-modules-all/README")
    files += ["%files -n pickle-modules-all", "%doc %{_docdir}/pickle-modules-all/README", ""]
    return "\n".join(packages), "\n".join(install), "\n".join(files)


def rpm_spec(spec_path, modules):
    packages, install, files = rpm_sections(modules)
    text = pathlib.Path(spec_path).read_text(encoding="utf-8")
    replacements = {"MODULE_PACKAGES": packages, "MODULE_INSTALL": install, "MODULE_FILES": files}
    for marker, body in replacements.items():
        pattern = re.compile(rf"^# @@{marker}@@[ \t]*$", re.MULTILINE)
        if not pattern.search(text):
            raise SystemExit(f"{spec_path} has no '# @@{marker}@@' line")
        text = pattern.sub(lambda _: body, text)
    return text


def main(argv):
    if len(argv) >= 2 and argv[1] == "wix":
        sys.stdout.write(wix(load()))
    elif len(argv) >= 3 and argv[1] == "rpm-spec":
        sys.stdout.write(rpm_spec(argv[2], load()))
    elif len(argv) >= 2 and argv[1] == "check":
        print(f"{len(load())} modules")
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main(sys.argv)
